name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      matrix:
        node: [ 14 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          npm install
          npm run bootstrap
      - name: Build packages
        run: |
          npm run build
          npm run bootstrap
      - name: Lint packages
        run: npm run lint
      - name: Test packages
        run: npm test
